CREATE TABLE IF NOT EXISTS device_daily_usage_counter (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id BIGINT, usage_date DATE, usage_count INT, version INT,
  create_time TIMESTAMP, update_time TIMESTAMP, create_by BIGINT, update_by BIGINT, is_deleted INT
);

CREATE TABLE IF NOT EXISTS device (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id VARCHAR(100), device_name VARCHAR(200), device_type VARCHAR(100),
  center_id BIGINT, center_name VARCHAR(200), state INT, connection_status INT,
  last_heartbeat TIMESTAMP, processing_minutes INT, remark VARCHAR(500),
  create_time TIMESTAMP, update_time TIMESTAMP, create_by BIGINT, update_by BIGINT, is_deleted INT
);

CREATE TABLE IF NOT EXISTS production_record (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  record_no VARCHAR(100), order_id BIGINT, order_code VARCHAR(100), order_type INT,
  design_package_id BIGINT, design_package_code VARCHAR(100), product_id BIGINT, product_name VARCHAR(255),
  product_category VARCHAR(100), product_category_name VARCHAR(255), production_batch_no VARCHAR(100), version_no VARCHAR(100),
  material VARCHAR(255), processing_center_id BIGINT, processing_center_name VARCHAR(255), producer_id BIGINT, producer_name VARCHAR(255),
  qc_id BIGINT, qc_name VARCHAR(255), print_device_id BIGINT, print_device_code VARCHAR(100), print_device_name VARCHAR(255),
  total_product_count INT, qualified_count INT, unqualified_count INT, status INT, current_process VARCHAR(100), qr_code_url VARCHAR(500),
  pack_device_id BIGINT, pack_device_no VARCHAR(100), pack_seal_temperature DECIMAL(10,2), pack_seal_time INT, pack_material VARCHAR(255),
  pack_sterilization_method VARCHAR(255), pack_sterilization_batch_no VARCHAR(255), pack_operator_id BIGINT, pack_operator_name VARCHAR(255), pack_time TIMESTAMP,
  material_batch_no VARCHAR(255), print_start_time TIMESTAMP, print_finish_time TIMESTAMP, post_processing_end_time TIMESTAMP,
  hospital_name VARCHAR(255), hospital_dept_name VARCHAR(255), doctor_name VARCHAR(255), patient_name VARCHAR(255), is_urgent INT, is_postal INT,
  expected_delivery_date TIMESTAMP, flow_card_file_url VARCHAR(500), flow_card_generate_time TIMESTAMP, content_update_time TIMESTAMP,
  create_time TIMESTAMP, update_time TIMESTAMP, create_by BIGINT, update_by BIGINT, is_deleted INT
);

CREATE TABLE IF NOT EXISTS production_product (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  production_record_id BIGINT, print_file_id BIGINT, product_no VARCHAR(100), product_name VARCHAR(255), spec_name VARCHAR(255),
  cert_no VARCHAR(255), material_name VARCHAR(255), color_name VARCHAR(255), file_name VARCHAR(255), weight DECIMAL(10,2), udi_code VARCHAR(255), udi_di VARCHAR(255), udi_pi VARCHAR(255),
  udi_generate_time TIMESTAMP, status VARCHAR(100), current_process_type VARCHAR(100), qc_result VARCHAR(100), qc_remark VARCHAR(500), qc_time TIMESTAMP,
  qc_user_id BIGINT, warehouse_in_time TIMESTAMP, warehouse_in_user_id BIGINT, warehouse_in_remark VARCHAR(500), warehouse_out_time TIMESTAMP,
  warehouse_out_user_id BIGINT, warehouse_out_remark VARCHAR(500), create_time TIMESTAMP, update_time TIMESTAMP, create_by BIGINT, update_by BIGINT, is_deleted INT
);
